### ISSUE TITLE
Versions past 1.6 buttons not working

### ISSUE THREAD

**Issue by dtrewren** [Efpophis/LDGControl#7] opened 2024-12-08 18:24 UTC
Hello there,
In versions 1.6/1.7 the Antenna/Full tune and Memory tune buttons are not working.  If I initiate a tune on the tuner itself I see the SW FWD and REF bar graphs operate so the connection is good.  however after hitting any button the application locks up.  I am uisng version 1.5 which does work but randomly locks up.  This issue with the buttons not working is the same issue reported by another user.

**Comment by Efpophis** [comment] 2024-12-16 14:17
This is very strange because version 1.5 barely works with my own LDG-1000ProII and the changes I made in the later versions have it working just about perfectly for me. I wonder if the issue could be a difference in tuner firmware or something like that?

Can you confirm if ANY of the button commands are working?

Also, unless you have a Flex radio and have the Flex integration feature active, the tuner control program will not key your transmitter - you have to do that yourself before the command times out. It doesn't sound like that's the missing piece, but it's worth mentioning.

**Comment by Efpophis** [comment] 2024-12-16 15:10
Hi again,

I am trying to debug this, which is difficult since it works perfectly on my computer with my tuner.

With that in mind, I have added a bunch of debug code to get some output that might tell me what's going on.

If you can, please install and run the attached version, connect to your tuner, and do a MEMORY tune -that is the button I've instrumented.  Please run the program from the command line, capture any output you see (there should be a lot), and post it here.
[Installer_debug_only.zip](https://github.com/user-attachments/files/18152409/Installer_debug_only.zip)

**Comment by ardugnome** [comment] 2024-12-16 15:19
Bill,Your latest vers did not for me either, we talked briefly about so I am using the old version, did not want to bug you too much. 
My symptoms are that the tuner does not tune, none of the buttons are functioning but cannot test it until tonight.
Relu 
 
  On Mon, Dec 16, 2024 at 9:11, Bill ***@***.***> wrote:   


Hi again,

I am trying to debug this, which is difficult since it works perfectly on my computer with my tuner.

With that in mind, I have added a bunch of debug code to get some output that might tell me what's going on.

If you can, please install and run the attached version, connect to your tuner, and do a MEMORY tune -that is the button I've instrumented. Please run the program from the command line, capture any output you see (there should be a lot), and post it here.
Installer_debug_only.zip

**Comment by Eugen68** [comment] 2024-12-16 16:37
Hello,
Ok, I installed the debug version you sent.
But I don't fully understand the procedure: after running the program and pressing the MEMORY tune button, where the debugging code appear?

**Comment by Efpophis** [comment] 2024-12-16 23:25
Hi again,
 (sorry  - you're not Eugene! ha ha)

You will need to open a command prompt and run the program from the command line. So you'd type `"C:\Program Files\" whatever path it's installed in \LDGControl.exe` in a windows command prompt and then the output should appear in that window once you hit "Memory Tune" in the GUI.

**Comment by Eugen68** [comment] 2024-12-17 05:40
Hi,
I thought I didn't understand the way the debugging program works, but nothing appears...
I have attached a print screen...
I don't understand what is wrong, maybe I'm missing something?

![debug ldg](https://github.com/user-attachments/assets/cec4f6eb-7ca6-4b36-8470-8120f7c99846)

**Comment by Eugen68** [comment] 2024-12-17 07:42
Hi again,
Finally, I monitored the serial port and captured the screen. You can notice that LDGControl does not send commands to the serial port.
Maybe on my computer, certain libraries that are necessary to run your software in good conditions, are not installed.

https://github.com/user-attachments/assets/03de4dde-a3ec-4566-b94e-965ec4bf182f

**Comment by dtrewren** [comment] 2024-12-17 17:53
Hi Bill,
I have connected my scope to both the Tx (data to LDG) and Rx (data from LDG).  Hitting the init button I see the app send an init byte and then 10.6ms later the LDG responds.  However, there is a second byte from the app which is sent to the LDG and this second byte wanders around sometimes occuring before the LDG response, sometimes during the response and sometimes after - it seems random in terms of position.  I have taken six scope screen shots as follows :

**Comment by dtrewren** [comment] 2024-12-17 17:55
This is the tuner working on a pre 1.6 app version:
![DS1Z_QuickPrint4](https://github.com/user-attachments/assets/5b5a5567-139e-4d5c-9cc3-46701f3846ef)

This shows the first app -> LDG byte:
![DS1Z_QuickPrint5](https://github.com/user-attachments/assets/613ffd82-7202-40b6-a64a-7f8de7dffe15)

This shows the second app -> LDG byte:
![DS1Z_QuickPrint6](https://github.com/user-attachments/assets/84c13b3a-1727-482b-b0b5-193c21a1afee)

**Comment by dtrewren** [comment] 2024-12-17 17:57
This shows the latest app verion (immediately before your debug version):
![DS1Z_QuickPrint1](https://github.com/user-attachments/assets/106edb89-0364-4449-b14e-aa705d180d50)

This shows the first app -> LDG byte:
![DS1Z_QuickPrint2](https://github.com/user-attachments/assets/fdf5dfff-56b9-4de3-bf1f-14b2ed75c52c)

This shows the second app -> LDG byte:
![DS1Z_QuickPrint3](https://github.com/user-attachments/assets/56801792-48f6-4419-991c-811a3682fa78)

**Comment by dtrewren** [comment] 2024-12-17 17:59
As you can see the init bytes are different between working and non working versions but the time from the first byte sent and the LDG responding is always the same at 10.6ms.  I am not sure what the second byte sent is and why is wanders about ?
Cheers,  Dave    G7IYK  (Bristol UK, check out my QRZ page).

Please let me know if you want further tests ?

I ran the latest version of the app 1.7.0.9 but the result was the same - no response from buttons after init 

I ran the latest version on the command line but all the happens is the app GUI is invoked the same as double clicking on LDGControl.exe.  How do I invoke the debug mode ?  Did this .exe come from the VS debug directory ?

**Comment by Efpophis** [comment] 2024-12-17 19:57
Hi Dave,

Thanks so much for this!  To answer a few of your questions:

1. The 1.7.0.9 is a release config build - no debug output there. It was too much of a PITA to get reliable console debug output outside of VS, so I took that stuff out.  If you have the latest VS Community edition (free), you can build the latest code in debug mode pretty easily and get the debug output yourself.
2. I would like to see what your scope shows when you hit the `memory tune` or any other button after init. Do you see any commands going out to the tuner at all?
3. Please verify that you have flex features disabled unless you have a flex rig on the network that you're using. I did find a potential for the program to try to talk to a flex rig even if one wasn't connected, which could result in a lockup. That should have been mitigated in 1.7.0.9, tho.
4. I did muck with the timing a little bit when sending any command to the tuner - I suspect the initialization you're seeing is a `wake` command (which is just a space) followed by a `meter` command ('S'). The 1.5 version would have sent 2 spaces for the wake, followed by an 'S', whereas 1.6 thru 1.7.0.8 only sent a single space. 1.7.0.9 is back to sending 2 spaces, but with adjusted timings.

I am using mine over a network connection in conjunction with my `socat server` project for the time being. I will have to try with a direct serial port connection and see if I can reproduce this issue.

Meanwhile, is there a feature in your scope software that will let you decode those bytes you're seeing?  I'd love to have confirmation of what's going out from the program each time.

**Comment by wcrossley** [comment] 2024-12-17 21:01
Actually - scratch most of that. I hooked my tuner up to my windows box and was able to reproduce the issue. I know exactly what's happening now, but I ran out of time to fix it this afternoon. 

I'll get to the bottom of it shortly, tho. QRX for a fix. 

73,

Bill WK2X

**Comment by Efpophis** [comment] 2024-12-18 00:59
It turns out that the Win32 serial port backend is weird. It will block `write` operations to the serial port if another thread is blocked on a read. The tcp socket API is not like this, which is why it still worked with my network-based connection. To further complicate things, the tcp side seems to break when I try to shift to non-blocking reads - I'm doing all the reads in a single thread with a polymorphic interface to the [serial or network] backend.

So fixing this without without screwing up the tcp side is going to be tricky. 

I'm about this close to saying `screw it` and rewriting the whole thing in Python...🤪

**Comment by Efpophis** [comment] 2024-12-18 04:13
Please try [Version 1.8.0.1](https://github.com/Efpophis/LDGControl/releases/tag/LDGControl_v1.8.0.1) - I believe I have fixed this issue. At the very least, it works again on my machine with a local serial port connection.

If it works for you, please close the issue.

73,

Bill WK2X

**Comment by dtrewren** [comment] 2024-12-18 16:32
Hello Bill,
I can also confirm that in the latest build the buttons are working and I can control the tuner.  One other thing I noticed - the bar graphs for FWD and REF power and SWR seem unresponsive ?  The tuner physical LEDs are dancing about during a tune but this is not reflected on the GUI ?

Good job getting the buttons to work !

Cheers,

                Dave   G7IYK

**Comment by Efpophis** [comment] 2024-12-18 17:39
Hi Dave,

Yeah, this is normal - I have to disable the meter telemetry during the tune because .. well, because the protocol is basically shyte :-p

I'm waiting for a response from the tuner to tell me if the match was `good`, `okay` or `bad` and that's a single-byte response. As such, it's indistinguishable from whatever random binary bytes are coming in as meter telemetry, and, indeed, it could arrive right smack in the middle of a meter message and I'd never know it. So, to get around this limitation, I've had to shut the meters off during tuning.

The way I have typically operated remotely is to do a tune, and then just transmit with the radio to see the results after the tune is complete.  It's not ideal, but given the comm protocol, it's probably the best I'm gonna be able to do.

IF I could get into the tuner firmware myself, I'd completely re-engineer the protocol so this wouldn't be an issue .. but LDG isn't interested in paying me to do that, so ... :-p  I think it's also the reason they left the meter telemetry off of their own GUI they developed shortly after I released my first version of this program, ha ha

All right - I'm going to go ahead and close this out.  Cheers!

**Closed as completed by Efpophis** 2024-12-18 17:39 UTC
